### ISSUE TITLE
Meetup API - Setup hero to sync with meetup API

### ISSUE THREAD

**Issue by HaydenBruin** [JuniorDev-TGA/JuniorDevTGA#25]
https://secure.meetup.com/meetup_api/console/?path=/:urlname/events

Use api to pull in latest event

**Comment by HaydenBruin** [comment]
Done, next event is displayed on the homepage hero

**Comment by Datacom-MichaelF** [comment]
Ha. Just realised this is already done. Whoops. Move along - nothing to see here
