### ISSUE TITLE
Landing page for Code Challenges

### ISSUE THREAD

**Issue by kellymarjorie** [JuniorDev-TGA/JuniorDevTGA#29]
Create a landing page for the code challenges.

Title: "Code Challenge" (or something better)
Three rectangle buttons vertically and horizontally centered in the page, for "Level 1", "Level 2", "Level 3".

Background yellow, text colours are the dark grey and purple from the backgrounds in the jdtga homepage.

A link at the bottom right of the page to go back to the JDTGA homepage.

**Comment by HaydenBruin** [comment]
https://jdtga.dev/stemfest2019/
