### ISSUE TITLE
Build HTML/CSS for slack channel

### ISSUE THREAD

**Issue by HaydenBruin** [JuniorDev-TGA/JuniorDevTGA#7]

**Comment by HaydenBruin** [comment]
@kellymarjorie can you provide the invite link for the slack channel.

**Comment by kellymarjorie** [comment]
Link is: https://join.slack.com/t/juniordevtga/shared_invite/enQtNDc3NjExOTk0NzA4LWM2NDM0N2EwNTIxZTNkNjM5ZGQ0NzM5ZmJhMGRhZGYwYjVhOWM4Y2Y1MWNjOTNmYjA2MTVjNjIyNDBhNDc2ZjY
