### ISSUE TITLE
Build HTML/CSS for header

### ISSUE THREAD

**Issue by HaydenBruin** [JuniorDev-TGA/JuniorDevTGA#8]

**Comment by HaydenBruin** [comment]
Navigation to slide to respective sections rather than new pages (sponsorship will be different, but will hide it for initial build).

**Comment by EmeraldSlash** [comment]
I think we should keep the sponsorship thing on the main page but keep it brief and just give a 'sponsor' button that takes you to another page with full details (otherwise clicking a link to another page would be confusing in the navigation when everything else goes to the same page)

**Comment by HaydenBruin** [comment]
Yeah good call! I'm happy to go ahead with that idea. Same pinky-red color as the title would look nice for the button.
